name: Run Litani Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    branches: [ release, develop ]

jobs:
  test-litani:
    if: "!contains(github.event.pull_request.labels.*.name, 'no-test')"
    name: Run Litani Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install ninja
          python3 -m pip install jinja2
      - name: Run Unit and e2e tests
        run: ./test/run
      - name: Upload bottles as artifact
        if: always()
        uses: actions/upload-artifact@main
        with:
          name: report
          path: 'test/output/latest/html'