name: Run Litani Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    branches: [ release, develop ]

jobs:
  test-litani:
    if: "!contains(github.event.pull_request.labels.*.name, 'no-test')"
    name: Run Litani Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install ninja
          python3 -m pip install jinja2

      - name: Run Unit and e2e tests
        run: ./test/run
        continue-on-error: true
        timeout-minutes: 5

      - name: Get absolute path to report dir
        run: echo "REPORT_PATH=$(readlink test/output/latest/html)" >> $GITHUB_ENV

      - name: Upload report as artifact
        uses: actions/upload-artifact@main
        if: always()
        with:
          name: Report
          path: ${{ env.REPORT_PATH }}
